"""
A module with an array of words
"""
words = ["albatross", "alligator", "alpaca", "ant", "axolotl",
         "baboon", "badger", "bat", "bear", "beaver", "bee", "bison",
         "bobcat", "buffalo", "camel", "cat", "clam", "cobra", "cougar",
         "camel", "caterpillar", "catfish", "cheetah", "chicken", "chimpanzee",
         "chinchilla", "chipmunk", "cow", "coyote", "crab", "crane", "cricket",
         "crocodile", "coyote", "crow", "cuckoo", "deer", "dingo", "dog",
         "dolphin", "donkey", "dragonfly", "duck", "dugong", "eagle", "eel",
         "elephant", "elk", "emu", "falcon", "ferret", "firefly", "flea",
         "flounder", "flamingo", "fox", "frog", "goat", "gazelle", "gecko",
         "gerbil", "goldfish", "goose", "gorilla", "hamster", "hare", "hawk",
         "hedgehog", "horse", "hummingburd", "hyena", "iguana", "impala",
         "jackal", "jaguar", "jellyfish", "kangaroo", "kiwi", "koala",
         "ladybug", "leech", "lemur", "lemming", "leopard", "lion", "lizard",
         "llama", "lobster", "lynx", "maggot", "magpie", "manatee", "meerkat",
         "mink", "mole", "monkey", "moose", "mosquito", "mouse", "mule",
         "narwhal", "newt", "nightingaleocelot", "octopus", "opossum",
         "ostrich", "otter", "owl", "oyster", "panda", "panther", "parrot",
         "peacock", "penguin", "pigeon", "pranha", "prawn", "porcupine",
         "puma", "python", "rabbit", "ram", "rat", "raven", "quokka",
         "quetzal", "rabbit", "raccoon", "rattlesnake", "reindeer",
         "rhino", "salmon", "scorpion", "seal", "shark", "sheep",
         "skunk", "sloth", "slug", "snake", "sparrow", "spider",
         "starfishstork", "swan", "tapir", "tiger", "toad",
         "trout", "tuna", "turkey", "turtle", "vulture", "walrus", "weasel",
         "whale", "wolf", "wolverine", "wombat", "worm", "yak", "zebra"]
